CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    uuid UUID NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    points INT DEFAULT 0 NOT NULL,
    referral BOOLEAN DEFAULT FALSE NOT NULL
);

