services:
#  user-manager:
#    user: root
#    build:
#      context: ..
#      dockerfile: ./deploy/Dockerfile
#    depends_on:
#      - postgres
#      - mongodb
#    networks:
#      - manager-network

  postgres:
    user: root
    image: bitnami/postgresql:16
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:?error}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME:?error}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE:?error}
    volumes:
      - ./pg-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}'" ]
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      - manager-network

  mongodb:
    user: root
    image: bitnami/mongodb:8.0.3
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/bitnami/mongodb
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME:?error}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:?error}
      MONGODB_DATABASE: ${MONGODB_DATABASE:?error}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:?error}
    networks:
      - manager-network

networks:
  manager-network:
    driver: bridge