services:
  postgres:
    user: root
    image: bitnami/postgresql:16
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:?error}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME:?error}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE:?error}
    volumes:
      - ./pg-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}'" ]
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      - manager-network

networks:
  manager-network:
    driver: bridge